### PR TITLE
8th revision of the language

### PR DESCRIPTION
**Pull request by zstanecic**
Here is the 8th revisio. It needs to be the part of apks.

### CODE REVIEW

**Comment by zstanecic** [comment]
Can we experiment by adding pseudo english flag to false? I don't have it included

**Comment by zstanecic** [comment]
Can we test this somehow on our phones with this change?

**Comment by Olga-Yakovleva** [comment]
For the moment the only way is the following:

1. Run ./build and upload the generated packages-latest.json somewhere 
on your server.

2. Change the value of the pkg_dir_url variable in the app in 
src/pkg/package_client.cpp and build the debug version of the app.

3. Install it and test.

**Comment by zstanecic** [comment]
well, trying to create our debug version using github action on the gh server
https://github.com/grzezlo/RHVoice/runs/5235524164?check_suite_focus=true

**Comment by Olga-Yakovleva** [comment]
That build now needs scons installed too. @alex19EP, I keep forgetting to ask you to add scons to that setup. I just don't have the time to figure out how to do the thing I'm using it for in Gradle, so I'm just calling scons from there.

**Comment by alex19EP** [comment]
> That build now needs scons installed too. @alex19EP, I keep forgetting to ask you to add scons to that setup. I just don't have the time to figure out how to do the thing I'm using it for in Gradle, so I'm just calling scons from there.

o I don't really like this... but will try adding scons tomorrow.

**Comment by Olga-Yakovleva** [comment]
This is now available in the alpha app.

**Pull request merged**
