### PR TITLE
Updated polish language package

### PR DESCRIPTION
**Pull request by zstanecic**
This is the last minute fix tested on windows. It fixes some pronunciation issues.
This is stable, and it is intended to merge to alpha, dev and stable straightforward.

### CODE REVIEW

**Comment by zstanecic** [comment]
Note: basic checks passed, language, and language=voice.

**Review by Olga-Yakovleva — APPROVED** [review]

**Comment by zstanecic** [comment]
Hi,

As I said, this doesn’t need to involve alpha testers. This can go to the alpha and stable simultaneously straightforward.

**Comment by Olga-Yakovleva** [comment]
Before I move this to stable, let's do a final sanity check. Please confirm that it is now working as expected in Alpha.

**Comment by Olga-Yakovleva** [comment]
Well, OK.

**Comment by Olga-Yakovleva** [comment]
Polish is now in the public app.

**Pull request merged**
