### PR TITLE
adding latest polish to beta

### PR DESCRIPTION
**Pull request by zstanecic**
This will make sure that RHvoice uses the new format

### CODE REVIEW

**Comment by Olga-Yakovleva** [comment]
This will have to wait a bit yet. As I said in my original announcement, 
my first priority is to be sure that the transition from the old to the 
new code is stable. There are very few people testing so far and no 
reports apart from yours.

**Comment by zstanecic** [comment]
Ok. I am waiting. In the meantime, can you confirm, that my json syntax is correct in all my work?

**Comment by Olga-Yakovleva** [comment]
Python can't parse one of your json files. Please run the build command 
and look at the traceback.

**Comment by Olga-Yakovleva** [comment]
Please merge the upstream main branch into this pr's branch.

**Comment by zstanecic** [comment]
Done!

**Comment by zstanecic** [comment]
Btw, Can you merge this tomorrow? I am planning to push more latest changes to the language pack.

**Comment by zstanecic** [comment]
Ok. I will fix this. Btw, In the evening, i am going to update the language pack along with 
@grzezlo

**Comment by zstanecic** [comment]
Now it passes the check, but i am planning one more update in the evening.

**Comment by Olga-Yakovleva** [comment]
OK, I will not merge yet then.

**Comment by zstanecic** [comment]
After merging of 
#479
from the main repo and updating json files here, this is good to go.

**Review by Olga-Yakovleva — APPROVED** [review]

**Comment by grzezlo** [comment]
After more investigations, some interesting facts:

- The problematic zip was generated by @zstanecic on the github servers, not locally.
- I thought that the files are identical, they are for the diff tool, but they have different line endings: problematic files, generated on github, have Windows crlf, and correctly working, have Windows lf.

**Comment by Olga-Yakovleva** [comment]
Thanks!

**Pull request merged**
