### PR TITLE
Spomenka - epo - voice update

### PR DESCRIPTION
**Pull request by zstanecic**
updated the spomenka voice. Soon i am going to update the packages.

### CODE REVIEW

**Comment by zstanecic** [comment]
i mean, sapi and NVDA ones.

**Comment by Olga-Yakovleva** [comment]
Published in Alpha.

**Comment by zstanecic** [comment]
I declare this ready for stable, because of the positive user’s feedback.

I gave my dev app to the small number of users, and they are satisfied by the voice quality and fixed errors.

**Comment by Olga-Yakovleva** [comment]
OK, it's published as stable as well.

**Pull request merged**
