### PR TITLE
Update of the polish and ukrainian voice

### PR DESCRIPTION
**Pull request by zstanecic**
Updated natan and Anatol.
As this has been tested and proven to work in the dev package before publishing, please release this in alpha and stable.

### CODE REVIEW

**Comment by zstanecic** [comment]
Note: this was checked and it's stable. Ready for production. Polish language is also updated to the new version.

**Comment by Olga-Yakovleva** [comment]
Anatol needs an updated revision number. You are reusing 4.1, which would mean no automatic upgrade for existing users.

**Comment by zstanecic** [comment]
Hi,

To fix this, I will need to recreate all packages. Users were warned that automatic upgrade is not possible.. 

Best,

zvonimir

**Comment by zstanecic** [comment]
And, this means, that I have the problem with recreating packages for all systems, not only android.

Best,

Zvonimir

**Comment by Olga-Yakovleva** [comment]
I will not merge a voice package with the same version number. This is a 
bug you need to fix.

**Comment by zstanecic** [comment]
Ok.

I will re-release the voice, respectively then at all.

Please, can you release languages for android?

I mean, Ukrainian and Russian.

So that I can align with these changes when building again.

**Comment by zstanecic** [comment]
Done. I have fixed all issues.

**Comment by zstanecic** [comment]
This Pr was replaced by the clean one.

**Comment by zstanecic** [comment]
This was fixed in my last commit now. You can merge this.

**Pull request closed without merging**
